import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def get_status_color(status):
    if 'Red' in status:
        return colors.red
    elif 'Yellow' in status:
        return colors.orange
    else:
        return colors.green

def generate_pdf_report(input_data, predictions, thresholds):
    """
    Generate a PDF report for a single prediction.
    predictions: list of dicts with keys: Target, Model, Value, Status
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    h2_style = styles['Heading2']
    normal_style = styles['Normal']
    
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.gray,
        italics=True
    )
    
    elements = []
    
    # Title
    elements.append(Paragraph("Gas Turbine Emissions Prediction Report", title_style))
    elements.append(Spacer(1, 12))
    
    # Meta Info
    elements.append(Paragraph(f"<b>Timestamp:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    elements.append(Spacer(1, 24))
    
    # Input Data Table
    elements.append(Paragraph("Input Sensor Readings", h2_style))
    input_data_list = [["Sensor", "Value"]]
    for k, v in input_data.items():
        input_data_list.append([k, f"{v:.4f}"])
        
    t_input = Table(input_data_list, colWidths=[200, 100])
    t_input.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(t_input)
    elements.append(Spacer(1, 24))
    
    # Predictions Table
    elements.append(Paragraph("Prediction Results", h2_style))
    pred_data_list = [["Target", "Model", "Predicted Value", "Status"]]
    
    for pred in predictions:
        pred_data_list.append([
            pred['Target'],
            pred['Model'],
            f"{pred['Value']:.4f}",
            pred['Status'].split(' ')[-1]
        ])
        
    t_pred = Table(pred_data_list, colWidths=[60, 150, 100, 80])
    
    # Dynamic styles for status
    t_pred_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]
    
    for i, pred in enumerate(predictions):
        row_idx = i + 1
        t_pred_style.append(('TEXTCOLOR', (3, row_idx), (3, row_idx), get_status_color(pred['Status'])))
        
    t_pred.setStyle(TableStyle(t_pred_style))
    elements.append(t_pred)
    elements.append(Spacer(1, 24))
    
    # Thresholds Info
    elements.append(Paragraph("Reference Thresholds", h2_style))
    thresh_data = [["Target", "Yellow (Warning)", "Red (Critical)"]]
    thresh_data.append(["CO", thresholds['CO']['yellow'], thresholds['CO']['red']])
    thresh_data.append(["NOx", thresholds['NOX']['yellow'], thresholds['NOX']['red']])
    
    t_thresh = Table(thresh_data, colWidths=[100, 120, 120])
    t_thresh.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(t_thresh)
    elements.append(Spacer(1, 36))
    
    # Disclaimer
    disclaimer = """
    DISCLAIMER: The threshold values used in this report are user-configurable reference thresholds 
    for monitoring purposes only. They DO NOT represent official environmental, regulatory, or legal limits. 
    This report is generated by an automated Machine Learning pipeline and should be verified by 
    domain experts before any operational decisions are made.
    """
    elements.append(Paragraph(disclaimer, disclaimer_style))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
